import Header from "@/components/Header";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | ResumeAI",
  description: "ResumeAI Terms of Service — rules and guidelines for using our service.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        <div className="prose prose-gray max-w-none text-sm text-gray-700 space-y-6">
          <p><strong>Effective Date:</strong> April 15, 2026</p>
          <p>By using ResumeAI (&ldquo;the Service&rdquo;), you agree to these Terms of Service. If you do not agree, do not use the Service.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">1. Service Description</h2>
          <p>ResumeAI provides AI-powered resume generation, ATS score checking, and PDF download services. Our AI generates resume content based on your input; you are responsible for reviewing and verifying all generated content for accuracy.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">2. User Responsibilities</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You must provide accurate personal information</li>
            <li>You are responsible for the content of your resume</li>
            <li>You must not use the Service for fraudulent purposes</li>
            <li>You must not misrepresent your qualifications or experience</li>
            <li>You must be at least 16 years old to use the Service</li>
          </ul>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">3. AI-Generated Content</h2>
          <p>Content generated by our AI is provided as a starting point. We do not guarantee that AI-generated resumes will result in job interviews or employment. You should review and customize all generated content before use.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">4. Payments and Refunds</h2>
          <p><strong>One-Time Purchase ($19):</strong> Grants you one PDF download without watermark. Non-refundable after download.</p>
          <p><strong>Pro Subscription ($9/month):</strong> Unlimited downloads, AI cover letters, and DOCX exports. Cancel anytime; access continues until the end of the billing period. Refunds for subscriptions are available within 7 days of initial purchase if no downloads have been made.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">5. Intellectual Property</h2>
          <p>You retain ownership of the personal information and content you provide. Generated resumes are yours to use. The ResumeAI platform, design, and technology are our intellectual property.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">6. Watermark</h2>
          <p>Free PDF downloads include a &ldquo;Created with ResumeAI&rdquo; watermark. Paid users receive watermark-free downloads. Removing the watermark from free downloads without payment is a violation of these terms.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">7. Limitation of Liability</h2>
          <p>ResumeAI is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to lost employment opportunities, inaccurate AI-generated content, or service interruptions.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">8. Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">9. Changes</h2>
          <p>We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

          <h2 className="text-lg font-semibold text-gray-900 mt-6">10. Contact</h2>
          <p>For questions about these terms: support@resumeai.site</p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
